// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dependencies": {
            "get": {
                "description": "list dependencies",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dependencies"
                ],
                "summary": "list dependencies",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "default 100, will be ignored if 'ids' is set",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 0, will be ignored if 'ids' is set",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter; ignores limit/offset; comma-seperated list",
                        "name": "ids",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/dependencymodel.Dependencies"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/dependencies/{id}": {
            "get": {
                "description": "get dependencies of deployment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dependencies"
                ],
                "summary": "get dependencies",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dependencymodel.Dependencies"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/v3/deployments": {
            "get": {
                "description": "list process deployments",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "list process deployments",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "default unlimited",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "default 0",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "default name.asc",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deploymentmodel.Deployment"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            },
            "post": {
                "description": "deploy process",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "deploy process",
                "parameters": [
                    {
                        "type": "string",
                        "description": "source of deployment (e.g. smart-service)",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "set to true to disable validation, that a service must be selected",
                        "name": "optional_service_selection",
                        "in": "query"
                    },
                    {
                        "description": "process deployment",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/deploymentmodel.Deployment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deploymentmodel.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/v3/deployments/{id}": {
            "get": {
                "description": "get process deployment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "get process deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "default true, omit SelectionOptions if set to false",
                        "name": "with_options",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deploymentmodel.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            },
            "put": {
                "description": "update process deployment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "update process deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "source of deployment (e.g. smart-service)",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "set to true to disable validation, that a service must be selected",
                        "name": "optional_service_selection",
                        "in": "query"
                    },
                    {
                        "description": "process deployment",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/deploymentmodel.Deployment"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deploymentmodel.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            },
            "delete": {
                "description": "delete process deployment",
                "tags": [
                    "deployment"
                ],
                "summary": "delete process deployment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "deployment id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/v3/prepared-deployments": {
            "post": {
                "description": "prepare process deployment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "prepare process deployment",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "default true, omit SelectionOptions if set to false",
                        "name": "with_options",
                        "in": "query"
                    },
                    {
                        "description": "model that should be prepared for deployment",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/messages.PrepareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deploymentmodel.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/v3/prepared-deployments/{modelId}": {
            "get": {
                "description": "prepare process deployment with model-id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "prepare process deployment with model-id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "process-model id",
                        "name": "modelId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "default true, omit SelectionOptions if set to false",
                        "name": "with_options",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/deploymentmodel.Deployment"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        },
        "/v3/start-parameters/{modelId}": {
            "get": {
                "description": "get start-parameters of a process-model",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "deployment"
                ],
                "summary": "get start-parameters",
                "parameters": [
                    {
                        "type": "string",
                        "description": "process-model id",
                        "name": "modelId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/deploymentmodel.ProcessStartParameter"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                },
                "security": [
                    {
                        "Bearer": []
                    }
                ]
            }
        }
    },
    "definitions": {
        "dependencymodel.BpmnResource": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dependencymodel.Dependencies": {
            "type": "object",
            "properties": {
                "deployment_id": {
                    "description": "from db",
                    "type": "string"
                },
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dependencymodel.DeviceDependency"
                    }
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dependencymodel.EventDependency"
                    }
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "dependencymodel.DeviceDependency": {
            "type": "object",
            "properties": {
                "bpmn_resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dependencymodel.BpmnResource"
                    }
                },
                "device_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dependencymodel.EventDependency": {
            "type": "object",
            "properties": {
                "bpmn_resources": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dependencymodel.BpmnResource"
                    }
                },
                "event_id": {
                    "type": "string"
                }
            }
        },
        "deploymentmodel.Deployment": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "diagram": {
                    "$ref": "#/definitions/models.Diagram"
                },
                "elements": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Element"
                    }
                },
                "executable": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "incident_handling": {
                    "$ref": "#/definitions/models.IncidentHandling"
                },
                "name": {
                    "type": "string"
                },
                "start_parameter": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ProcessStartParameter"
                    }
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "deploymentmodel.ProcessStartParameter": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "messages.PrepareRequest": {
            "type": "object",
            "properties": {
                "svg": {
                    "type": "string"
                },
                "xml": {
                    "type": "string"
                }
            }
        },
        "models.AspectNode": {
            "type": "object",
            "properties": {
                "ancestor_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "aspect_class_id": {
                    "type": "string"
                },
                "child_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "descendent_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parent_id": {
                    "type": "string"
                },
                "root_id": {
                    "type": "string"
                }
            }
        },
        "models.ConditionalEvent": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "qos": {
                    "type": "integer"
                },
                "script": {
                    "type": "string"
                },
                "selection": {
                    "$ref": "#/definitions/models.Selection"
                },
                "value_variable": {
                    "type": "string"
                },
                "variables": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "models.Configurable": {
            "type": "object",
            "properties": {
                "aspect_node": {
                    "description": "deprecated: alias for a single element AspectNodes; holds the node with the alphabetically first id",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AspectNode"
                        }
                    ]
                },
                "aspect_nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AspectNode"
                    }
                },
                "characteristic_id": {
                    "type": "string"
                },
                "function_id": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.Type"
                },
                "value": {}
            }
        },
        "models.Diagram": {
            "type": "object",
            "properties": {
                "svg": {
                    "type": "string"
                },
                "xml_deployed": {
                    "type": "string"
                },
                "xml_raw": {
                    "type": "string"
                }
            }
        },
        "models.Element": {
            "type": "object",
            "properties": {
                "bpmn_id": {
                    "type": "string"
                },
                "conditional_event": {
                    "$ref": "#/definitions/models.ConditionalEvent"
                },
                "group": {
                    "type": "string"
                },
                "message_event": {
                    "$ref": "#/definitions/models.MessageEvent"
                },
                "name": {
                    "type": "string"
                },
                "notification": {
                    "$ref": "#/definitions/models.Notification"
                },
                "order": {
                    "type": "integer"
                },
                "task": {
                    "$ref": "#/definitions/models.Task"
                },
                "time_event": {
                    "$ref": "#/definitions/models.TimeEvent"
                }
            }
        },
        "models.GenericEventSource": {
            "type": "object",
            "properties": {
                "filter_ids": {
                    "type": "string"
                },
                "filter_type": {
                    "type": "string"
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "models.Import": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ImportConfig"
                    }
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "import_type_id": {
                    "type": "string"
                },
                "kafka_topic": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "restart": {
                    "type": "boolean"
                }
            }
        },
        "models.ImportConfig": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "value": {}
            }
        },
        "models.ImportContentVariable": {
            "type": "object",
            "properties": {
                "aspect_id": {
                    "description": "deprecated: please use AspectIds",
                    "type": "string"
                },
                "aspect_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "characteristic_id": {
                    "type": "string"
                },
                "function_id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sub_content_variables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ImportContentVariable"
                    }
                },
                "type": {
                    "$ref": "#/definitions/models.Type"
                },
                "use_as_tag": {
                    "type": "boolean"
                }
            }
        },
        "models.ImportType": {
            "type": "object",
            "properties": {
                "configs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ImportTypeConfig"
                    }
                },
                "cost": {
                    "type": "integer"
                },
                "default_restart": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "output": {
                    "$ref": "#/definitions/models.ImportContentVariable"
                },
                "owner": {
                    "type": "string"
                }
            }
        },
        "models.ImportTypeConfig": {
            "type": "object",
            "properties": {
                "default_value": {},
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.Type"
                }
            }
        },
        "models.IncidentHandling": {
            "type": "object",
            "properties": {
                "notify": {
                    "type": "boolean"
                },
                "restart": {
                    "type": "boolean"
                }
            }
        },
        "models.Interaction": {
            "type": "string",
            "enum": [
                "event",
                "request",
                "event+request"
            ],
            "x-enum-varnames": [
                "EVENT",
                "REQUEST",
                "EVENT_AND_REQUEST"
            ]
        },
        "models.MessageEvent": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "flow_id": {
                    "type": "string"
                },
                "selection": {
                    "$ref": "#/definitions/models.Selection"
                },
                "use_marshaller": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "models.Notification": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "models.PathOption": {
            "type": "object",
            "properties": {
                "aspectNode": {
                    "description": "deprecated: alias for a single element AspectNodes; holds the node with the alphabetically first id",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AspectNode"
                        }
                    ]
                },
                "aspectNodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AspectNode"
                    }
                },
                "characteristicId": {
                    "type": "string"
                },
                "configurables": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Configurable"
                    }
                },
                "functionId": {
                    "type": "string"
                },
                "interaction": {
                    "$ref": "#/definitions/models.Interaction"
                },
                "isVoid": {
                    "type": "boolean"
                },
                "path": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.Type"
                },
                "value": {}
            }
        },
        "models.ProcessFilterCriteria": {
            "type": "object",
            "properties": {
                "aspect_id": {
                    "description": "deprecated: please use AspectIds",
                    "type": "string"
                },
                "aspect_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "characteristic_id": {
                    "type": "string"
                },
                "device_class_id": {
                    "type": "string"
                },
                "function_id": {
                    "type": "string"
                }
            }
        },
        "models.ProcessStartParameter": {
            "type": "object",
            "properties": {
                "default": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.Selection": {
            "type": "object",
            "properties": {
                "filter_criteria": {
                    "$ref": "#/definitions/models.ProcessFilterCriteria"
                },
                "selected_device_group_id": {
                    "type": "string"
                },
                "selected_device_id": {
                    "type": "string"
                },
                "selected_generic_event_source": {
                    "$ref": "#/definitions/models.GenericEventSource"
                },
                "selected_import_id": {
                    "type": "string"
                },
                "selected_path": {
                    "$ref": "#/definitions/models.PathOption"
                },
                "selected_service_id": {
                    "type": "string"
                },
                "selection_options": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SelectionOption"
                    }
                }
            }
        },
        "models.SelectionDevice": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.SelectionDeviceGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.SelectionOption": {
            "type": "object",
            "properties": {
                "device": {
                    "$ref": "#/definitions/models.SelectionDevice"
                },
                "device_group": {
                    "$ref": "#/definitions/models.SelectionDeviceGroup"
                },
                "import": {
                    "$ref": "#/definitions/models.Import"
                },
                "importType": {
                    "$ref": "#/definitions/models.ImportType"
                },
                "path_options": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/models.PathOption"
                        }
                    }
                },
                "services": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SelectionService"
                    }
                }
            }
        },
        "models.SelectionService": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "models.Task": {
            "type": "object",
            "properties": {
                "parameter": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "prefer_event": {
                    "type": "boolean"
                },
                "retries": {
                    "type": "integer"
                },
                "selection": {
                    "$ref": "#/definitions/models.Selection"
                }
            }
        },
        "models.TimeEvent": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "models.Type": {
            "type": "string",
            "enum": [
                "https://schema.org/Text",
                "https://schema.org/Integer",
                "https://schema.org/Float",
                "https://schema.org/Boolean",
                "https://schema.org/ItemList",
                "https://schema.org/StructuredValue"
            ],
            "x-enum-varnames": [
                "String",
                "Integer",
                "Float",
                "Boolean",
                "List",
                "Structure"
            ]
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Process-Deployment API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
